"""Wire-protocol primitives: constants, message envelopes, type guards.

Mirrors ``bifrost-ts/src/utils/constants.ts`` and
``bifrost-ts/src/utils/protocol.ts``.
"""

from bifrost.protocol.constants import (
    BIFROST_WS_PATH,
    CLIENT_ID_HEADER_KEY,
    HTTP_ENDPOINT_PATH,
    NO_CHANNEL,
    TOKEN_HEADER_KEY,
    BifrostEvents,
    ClientEvents,
    Methods,
    RedisListeners,
    ServerEvents,
    WebSocketEvents,
    WebSocketState,
)
from bifrost.protocol.messages import (
    AuthMessage,
    ClientMessage,
    EventMessage,
    MessageType,
    PayloadType,
    PingMessage,
    PongMessage,
    RpcMessage,
    RpcResponseError,
    RpcResponseMessage,
    RpcResponseSuccess,
    RpcVoidMessage,
    ServerMessage,
    WireMessage,
    is_auth_message,
    is_event_message,
    is_ping_message,
    is_pong_message,
    is_rpc_message,
    is_rpc_response,
    is_rpc_void_message,
)

__all__ = [
    "BIFROST_WS_PATH",
    "CLIENT_ID_HEADER_KEY",
    "HTTP_ENDPOINT_PATH",
    "NO_CHANNEL",
    "TOKEN_HEADER_KEY",
    "AuthMessage",
    "BifrostEvents",
    "ClientEvents",
    "ClientMessage",
    "EventMessage",
    "MessageType",
    "Methods",
    "PayloadType",
    "PingMessage",
    "PongMessage",
    "RedisListeners",
    "RpcMessage",
    "RpcResponseError",
    "RpcResponseMessage",
    "RpcResponseSuccess",
    "RpcVoidMessage",
    "ServerEvents",
    "ServerMessage",
    "WebSocketEvents",
    "WebSocketState",
    "WireMessage",
    "is_auth_message",
    "is_event_message",
    "is_ping_message",
    "is_pong_message",
    "is_rpc_message",
    "is_rpc_response",
    "is_rpc_void_message",
]
