# frozen_string_literal: true

source "https://rubygems.org"

gemspec

gem "minitest", "~> 5.25"
gem "rack-test", "~> 2.2"
gem "rake", "~> 13.2"
gem "rbs", "~> 3.9"
gem "standard", "~> 1.50"
gem "steep", "~> 1.10"
