# frozen_string_literal: true

require "bundler/gem_tasks"
require "rake/testtask"

Rake::TestTask.new(:test) do |task|
  task.libs << "lib"
  task.libs << "test"
  task.pattern = "test/**/*_test.rb"
end

namespace :test do
  Rake::TestTask.new(:unit) do |task|
    task.libs << "lib"
    task.libs << "test"
    task.pattern = "test/unit/**/*_test.rb"
  end

  Rake::TestTask.new(:conformance) do |task|
    task.libs << "lib"
    task.libs << "test"
    task.pattern = "test/conformance/**/*_test.rb"
  end

  Rake::TestTask.new(:integration) do |task|
    task.libs << "lib"
    task.libs << "test"
    task.pattern = "test/integration/**/*_test.rb"
  end
end

desc "Check RBS signatures against Ruby implementation"
task :typecheck do
  sh "bundle exec steep check"
end

desc "Check Ruby formatting and style"
task :lint do
  sh "bundle exec standardrb"
end

desc "Build and verify the gem artifact"
task package: :build do
  sh "ruby test/support/verify_package.rb"
end

desc "Run the complete Ruby verification gate"
task verify: [:test, :typecheck, :lint, :package]

task default: :verify
