#!/usr/bin/env ruby
# frozen_string_literal: true

require "rbconfig"
require "socket"
require "timeout"

root = File.expand_path("..", __dir__)
port = Integer(ENV.fetch("TYPEFERRY_PORT", "0"))
if port.zero?
  probe = TCPServer.new("127.0.0.1", 0)
  port = probe.local_address.ip_port
  probe.close
end

config = File.join(root, "examples", "rack_app.ru")
command = [RbConfig.ruby, Gem.bin_path("puma", "puma"), "--quiet", "--bind", "tcp://127.0.0.1:#{port}", config]
child = Process.spawn(*command, chdir: root, out: $stderr, err: $stderr)

shutdown = lambda do
  Process.kill("TERM", child)
rescue Errno::ESRCH
  nil
end

Signal.trap("TERM", &shutdown)
Signal.trap("INT", &shutdown)

Timeout.timeout(15) do
  loop do
    socket = TCPSocket.new("127.0.0.1", port)
    socket.close
    break
  rescue Errno::ECONNREFUSED
    raise "Puma exited before readiness" unless Process.waitpid(child, Process::WNOHANG).nil?

    sleep 0.02
  end
end

warn("TYPEFERRY_PORT=#{port}")
Process.wait(child)
